// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Direct (unpooled) connection — the schema engine (migrate/introspect) needs a plain
    // TCP connection, not Neon's pooled/WebSocket endpoint used by the app at runtime.
    url: process.env["DIRECT_URL"],
  },
});
